/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKconfigBindings implements KconfigBindingInterface
type FakeKconfigBindings struct {
	Fake *FakeKconfigcontrollerV1alpha1
	ns   string
}

var kconfigbindingsResource = schema.GroupVersionResource{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Resource: "kconfigbindings"}

var kconfigbindingsKind = schema.GroupVersionKind{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Kind: "KconfigBinding"}

// Get takes name of the kconfigBinding, and returns the corresponding kconfigBinding object, and an error if there is any.
func (c *FakeKconfigBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.KconfigBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(kconfigbindingsResource, c.ns, name), &v1alpha1.KconfigBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KconfigBinding), err
}

// List takes label and field selectors, and returns the list of KconfigBindings that match those selectors.
func (c *FakeKconfigBindings) List(opts v1.ListOptions) (result *v1alpha1.KconfigBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(kconfigbindingsResource, kconfigbindingsKind, c.ns, opts), &v1alpha1.KconfigBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KconfigBindingList{ListMeta: obj.(*v1alpha1.KconfigBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.KconfigBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested kconfigBindings.
func (c *FakeKconfigBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(kconfigbindingsResource, c.ns, opts))

}

// Create takes the representation of a kconfigBinding and creates it.  Returns the server's representation of the kconfigBinding, and an error, if there is any.
func (c *FakeKconfigBindings) Create(kconfigBinding *v1alpha1.KconfigBinding) (result *v1alpha1.KconfigBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(kconfigbindingsResource, c.ns, kconfigBinding), &v1alpha1.KconfigBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KconfigBinding), err
}

// Update takes the representation of a kconfigBinding and updates it. Returns the server's representation of the kconfigBinding, and an error, if there is any.
func (c *FakeKconfigBindings) Update(kconfigBinding *v1alpha1.KconfigBinding) (result *v1alpha1.KconfigBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(kconfigbindingsResource, c.ns, kconfigBinding), &v1alpha1.KconfigBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KconfigBinding), err
}

// Delete takes name of the kconfigBinding and deletes it. Returns an error if one occurs.
func (c *FakeKconfigBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(kconfigbindingsResource, c.ns, name), &v1alpha1.KconfigBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKconfigBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(kconfigbindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KconfigBindingList{})
	return err
}

// Patch applies the patch and returns the patched kconfigBinding.
func (c *FakeKconfigBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KconfigBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(kconfigbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.KconfigBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KconfigBinding), err
}
