/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeStatefulSetBindings implements StatefulSetBindingInterface
type FakeStatefulSetBindings struct {
	Fake *FakeKconfigcontrollerV1alpha1
	ns   string
}

var statefulsetbindingsResource = schema.GroupVersionResource{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Resource: "statefulsetbindings"}

var statefulsetbindingsKind = schema.GroupVersionKind{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Kind: "StatefulSetBinding"}

// Get takes name of the statefulSetBinding, and returns the corresponding statefulSetBinding object, and an error if there is any.
func (c *FakeStatefulSetBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.StatefulSetBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(statefulsetbindingsResource, c.ns, name), &v1alpha1.StatefulSetBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetBinding), err
}

// List takes label and field selectors, and returns the list of StatefulSetBindings that match those selectors.
func (c *FakeStatefulSetBindings) List(opts v1.ListOptions) (result *v1alpha1.StatefulSetBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(statefulsetbindingsResource, statefulsetbindingsKind, c.ns, opts), &v1alpha1.StatefulSetBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.StatefulSetBindingList{ListMeta: obj.(*v1alpha1.StatefulSetBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.StatefulSetBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested statefulSetBindings.
func (c *FakeStatefulSetBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(statefulsetbindingsResource, c.ns, opts))

}

// Create takes the representation of a statefulSetBinding and creates it.  Returns the server's representation of the statefulSetBinding, and an error, if there is any.
func (c *FakeStatefulSetBindings) Create(statefulSetBinding *v1alpha1.StatefulSetBinding) (result *v1alpha1.StatefulSetBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(statefulsetbindingsResource, c.ns, statefulSetBinding), &v1alpha1.StatefulSetBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetBinding), err
}

// Update takes the representation of a statefulSetBinding and updates it. Returns the server's representation of the statefulSetBinding, and an error, if there is any.
func (c *FakeStatefulSetBindings) Update(statefulSetBinding *v1alpha1.StatefulSetBinding) (result *v1alpha1.StatefulSetBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(statefulsetbindingsResource, c.ns, statefulSetBinding), &v1alpha1.StatefulSetBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetBinding), err
}

// Delete takes name of the statefulSetBinding and deletes it. Returns an error if one occurs.
func (c *FakeStatefulSetBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(statefulsetbindingsResource, c.ns, name), &v1alpha1.StatefulSetBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeStatefulSetBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(statefulsetbindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.StatefulSetBindingList{})
	return err
}

// Patch applies the patch and returns the patched statefulSetBinding.
func (c *FakeStatefulSetBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StatefulSetBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(statefulsetbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.StatefulSetBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.StatefulSetBinding), err
}
