/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDeploymentBindings implements DeploymentBindingInterface
type FakeDeploymentBindings struct {
	Fake *FakeKconfigcontrollerV1alpha1
	ns   string
}

var deploymentbindingsResource = schema.GroupVersionResource{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Resource: "deploymentbindings"}

var deploymentbindingsKind = schema.GroupVersionKind{Group: "kconfigcontroller.atteg.com", Version: "v1alpha1", Kind: "DeploymentBinding"}

// Get takes name of the deploymentBinding, and returns the corresponding deploymentBinding object, and an error if there is any.
func (c *FakeDeploymentBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.DeploymentBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(deploymentbindingsResource, c.ns, name), &v1alpha1.DeploymentBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentBinding), err
}

// List takes label and field selectors, and returns the list of DeploymentBindings that match those selectors.
func (c *FakeDeploymentBindings) List(opts v1.ListOptions) (result *v1alpha1.DeploymentBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(deploymentbindingsResource, deploymentbindingsKind, c.ns, opts), &v1alpha1.DeploymentBindingList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DeploymentBindingList{ListMeta: obj.(*v1alpha1.DeploymentBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.DeploymentBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested deploymentBindings.
func (c *FakeDeploymentBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(deploymentbindingsResource, c.ns, opts))

}

// Create takes the representation of a deploymentBinding and creates it.  Returns the server's representation of the deploymentBinding, and an error, if there is any.
func (c *FakeDeploymentBindings) Create(deploymentBinding *v1alpha1.DeploymentBinding) (result *v1alpha1.DeploymentBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(deploymentbindingsResource, c.ns, deploymentBinding), &v1alpha1.DeploymentBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentBinding), err
}

// Update takes the representation of a deploymentBinding and updates it. Returns the server's representation of the deploymentBinding, and an error, if there is any.
func (c *FakeDeploymentBindings) Update(deploymentBinding *v1alpha1.DeploymentBinding) (result *v1alpha1.DeploymentBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(deploymentbindingsResource, c.ns, deploymentBinding), &v1alpha1.DeploymentBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentBinding), err
}

// Delete takes name of the deploymentBinding and deletes it. Returns an error if one occurs.
func (c *FakeDeploymentBindings) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(deploymentbindingsResource, c.ns, name), &v1alpha1.DeploymentBinding{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDeploymentBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(deploymentbindingsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DeploymentBindingList{})
	return err
}

// Patch applies the patch and returns the patched deploymentBinding.
func (c *FakeDeploymentBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DeploymentBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(deploymentbindingsResource, c.ns, name, pt, data, subresources...), &v1alpha1.DeploymentBinding{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DeploymentBinding), err
}
