/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	scheme "github.com/gbraxton/kconfig/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KconfigBindingsGetter has a method to return a KconfigBindingInterface.
// A group's client should implement this interface.
type KconfigBindingsGetter interface {
	KconfigBindings(namespace string) KconfigBindingInterface
}

// KconfigBindingInterface has methods to work with KconfigBinding resources.
type KconfigBindingInterface interface {
	Create(*v1alpha1.KconfigBinding) (*v1alpha1.KconfigBinding, error)
	Update(*v1alpha1.KconfigBinding) (*v1alpha1.KconfigBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KconfigBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.KconfigBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KconfigBinding, err error)
	KconfigBindingExpansion
}

// kconfigBindings implements KconfigBindingInterface
type kconfigBindings struct {
	client rest.Interface
	ns     string
}

// newKconfigBindings returns a KconfigBindings
func newKconfigBindings(c *KconfigcontrollerV1alpha1Client, namespace string) *kconfigBindings {
	return &kconfigBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kconfigBinding, and returns the corresponding kconfigBinding object, and an error if there is any.
func (c *kconfigBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.KconfigBinding, err error) {
	result = &v1alpha1.KconfigBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kconfigbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KconfigBindings that match those selectors.
func (c *kconfigBindings) List(opts v1.ListOptions) (result *v1alpha1.KconfigBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KconfigBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kconfigbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kconfigBindings.
func (c *kconfigBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kconfigbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kconfigBinding and creates it.  Returns the server's representation of the kconfigBinding, and an error, if there is any.
func (c *kconfigBindings) Create(kconfigBinding *v1alpha1.KconfigBinding) (result *v1alpha1.KconfigBinding, err error) {
	result = &v1alpha1.KconfigBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kconfigbindings").
		Body(kconfigBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kconfigBinding and updates it. Returns the server's representation of the kconfigBinding, and an error, if there is any.
func (c *kconfigBindings) Update(kconfigBinding *v1alpha1.KconfigBinding) (result *v1alpha1.KconfigBinding, err error) {
	result = &v1alpha1.KconfigBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kconfigbindings").
		Name(kconfigBinding.Name).
		Body(kconfigBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the kconfigBinding and deletes it. Returns an error if one occurs.
func (c *kconfigBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kconfigbindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kconfigBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kconfigbindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kconfigBinding.
func (c *kconfigBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KconfigBinding, err error) {
	result = &v1alpha1.KconfigBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kconfigbindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
