/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	scheme "github.com/gbraxton/kconfig/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KconfigsGetter has a method to return a KconfigInterface.
// A group's client should implement this interface.
type KconfigsGetter interface {
	Kconfigs(namespace string) KconfigInterface
}

// KconfigInterface has methods to work with Kconfig resources.
type KconfigInterface interface {
	Create(*v1alpha1.Kconfig) (*v1alpha1.Kconfig, error)
	Update(*v1alpha1.Kconfig) (*v1alpha1.Kconfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Kconfig, error)
	List(opts v1.ListOptions) (*v1alpha1.KconfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kconfig, err error)
	KconfigExpansion
}

// kconfigs implements KconfigInterface
type kconfigs struct {
	client rest.Interface
	ns     string
}

// newKconfigs returns a Kconfigs
func newKconfigs(c *KconfigcontrollerV1alpha1Client, namespace string) *kconfigs {
	return &kconfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the kconfig, and returns the corresponding kconfig object, and an error if there is any.
func (c *kconfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.Kconfig, err error) {
	result = &v1alpha1.Kconfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Kconfigs that match those selectors.
func (c *kconfigs) List(opts v1.ListOptions) (result *v1alpha1.KconfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.KconfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("kconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested kconfigs.
func (c *kconfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("kconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a kconfig and creates it.  Returns the server's representation of the kconfig, and an error, if there is any.
func (c *kconfigs) Create(kconfig *v1alpha1.Kconfig) (result *v1alpha1.Kconfig, err error) {
	result = &v1alpha1.Kconfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("kconfigs").
		Body(kconfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a kconfig and updates it. Returns the server's representation of the kconfig, and an error, if there is any.
func (c *kconfigs) Update(kconfig *v1alpha1.Kconfig) (result *v1alpha1.Kconfig, err error) {
	result = &v1alpha1.Kconfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("kconfigs").
		Name(kconfig.Name).
		Body(kconfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the kconfig and deletes it. Returns an error if one occurs.
func (c *kconfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *kconfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("kconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched kconfig.
func (c *kconfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Kconfig, err error) {
	result = &v1alpha1.Kconfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("kconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
