/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by main. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	scheme "github.com/gbraxton/kconfig/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// StatefulSetBindingsGetter has a method to return a StatefulSetBindingInterface.
// A group's client should implement this interface.
type StatefulSetBindingsGetter interface {
	StatefulSetBindings(namespace string) StatefulSetBindingInterface
}

// StatefulSetBindingInterface has methods to work with StatefulSetBinding resources.
type StatefulSetBindingInterface interface {
	Create(*v1alpha1.StatefulSetBinding) (*v1alpha1.StatefulSetBinding, error)
	Update(*v1alpha1.StatefulSetBinding) (*v1alpha1.StatefulSetBinding, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.StatefulSetBinding, error)
	List(opts v1.ListOptions) (*v1alpha1.StatefulSetBindingList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StatefulSetBinding, err error)
	StatefulSetBindingExpansion
}

// statefulSetBindings implements StatefulSetBindingInterface
type statefulSetBindings struct {
	client rest.Interface
	ns     string
}

// newStatefulSetBindings returns a StatefulSetBindings
func newStatefulSetBindings(c *KconfigcontrollerV1alpha1Client, namespace string) *statefulSetBindings {
	return &statefulSetBindings{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the statefulSetBinding, and returns the corresponding statefulSetBinding object, and an error if there is any.
func (c *statefulSetBindings) Get(name string, options v1.GetOptions) (result *v1alpha1.StatefulSetBinding, err error) {
	result = &v1alpha1.StatefulSetBinding{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of StatefulSetBindings that match those selectors.
func (c *statefulSetBindings) List(opts v1.ListOptions) (result *v1alpha1.StatefulSetBindingList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.StatefulSetBindingList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested statefulSetBindings.
func (c *statefulSetBindings) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a statefulSetBinding and creates it.  Returns the server's representation of the statefulSetBinding, and an error, if there is any.
func (c *statefulSetBindings) Create(statefulSetBinding *v1alpha1.StatefulSetBinding) (result *v1alpha1.StatefulSetBinding, err error) {
	result = &v1alpha1.StatefulSetBinding{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		Body(statefulSetBinding).
		Do().
		Into(result)
	return
}

// Update takes the representation of a statefulSetBinding and updates it. Returns the server's representation of the statefulSetBinding, and an error, if there is any.
func (c *statefulSetBindings) Update(statefulSetBinding *v1alpha1.StatefulSetBinding) (result *v1alpha1.StatefulSetBinding, err error) {
	result = &v1alpha1.StatefulSetBinding{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		Name(statefulSetBinding.Name).
		Body(statefulSetBinding).
		Do().
		Into(result)
	return
}

// Delete takes name of the statefulSetBinding and deletes it. Returns an error if one occurs.
func (c *statefulSetBindings) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *statefulSetBindings) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("statefulsetbindings").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched statefulSetBinding.
func (c *statefulSetBindings) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.StatefulSetBinding, err error) {
	result = &v1alpha1.StatefulSetBinding{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("statefulsetbindings").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
