# permissions to do edit kconfigbindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kconfigbinding-editor-role
rules:
- apiGroups:
  - kconfigcontroller.atteg.com
  resources:
  - kconfigbindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kconfigcontroller.atteg.com
  resources:
  - kconfigbindings/status
  verbs:
  - get
  - patch
  - update
