---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kconfigcontroller.atteg.com
  resources:
  - kconfigbindings
  - kconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kconfigcontroller.atteg.com
  resources:
  - kconfigbindings/finalizers
  - kconfigs/finalizers
  verbs:
  - update
- apiGroups:
  - kconfigcontroller.atteg.com
  resources:
  - kconfigbindings/status
  - kconfigs/status
  verbs:
  - get
  - patch
  - update
