apiVersion: kconfigcontroller.atteg.com/v1beta1
kind: KconfigBinding
metadata:
  labels:
    app.kubernetes.io/name: kconfigbinding
    app.kubernetes.io/instance: kconfigbinding-sample
    app.kubernetes.io/part-of: kconfig-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kconfig-controller
  name: kconfigbinding-sample
spec:
  # TODO(user): Add fields here
