apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: kconfigs.kconfigcontroller.atteg.com
spec:
  group: kconfigcontroller.atteg.com
  versions:
  - name: v1alpha1
    served: true
    storage: true
  version: v1alpha1
  scope: Namespaced
  names:
    plural: kconfigs
    singular: kconfig
    kind: Kconfig
    shortNames:
    - kc
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
          required: ["level"]
          properties:
            level:
              type: integer
              minimum: 1
              maximum: 99
            envConfigs:
              type: array
              items:
                properties:
                  type:
                    type: string
                  key:
                    type: string
                    pattern: '^[a-zA-Z_][a-zA-Z0-9_]*$'
                  value:
                    type: string
                  refName:
                    type: string
                  refKey:
                    type: string
            envRefsVersion:
                type: integer

---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: deploymentbindings.kconfigcontroller.atteg.com
spec:
  group: kconfigcontroller.atteg.com
  names:
    kind: DeploymentBinding
    listKind: DeploymentBindingList
    plural: deploymentbindings
    singular: deploymentbinding
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: statefulsetbindings.kconfigcontroller.atteg.com
spec:
  group: kconfigcontroller.atteg.com
  names:
    kind: StatefulSetBinding
    listKind: StatefulSetBindingList
    plural: statefulsetbindings
    singular: statefulsetbinding
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: knativeservicebindings.kconfigcontroller.atteg.com
spec:
  group: kconfigcontroller.atteg.com
  names:
    kind: KnativeServiceBinding
    listKind: KnativeServiceBindingList
    plural: knativeservicebindings
    singular: knativeservicebinding
  scope: Namespaced
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}