apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: common-system
  name: kconfig-controller-manager
spec:
  selector:
    matchLabels:
      app: kconfig-controller-manager
  template:
    metadata:
      labels:
        app: kconfig-controller-manager
    spec:
      containers:
      - name: kconfig-controller-manager
        args:
        - --logtostderr=true
        - -v=5
        image: docker-registry.aeg.cloud/common-system/kconfig-controller:v0.3.0-alpha-1
        resources:
          requests:
            memory: 2Gi
            cpu: 2
          limits:
            memory: 2Gi
            cpu: 2
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          failureThreshold: 3
          successThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
      serviceAccountName: kconfig-controller-manager
