apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kconfig-controller-manager
rules:
- apiGroups:
  - "apps"
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - events
  - configmaps
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - "kconfigcontroller.atteg.com"
  resources:
  - kconfigs
  - kconfigbindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kconfig-controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kconfig-controller-manager
subjects:
- kind: ServiceAccount
  name: kconfig-controller-manager
  namespace: kube-system