/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	kconfigcontrollerv1alpha1 "github.com/gbraxton/kconfig/pkg/apis/kconfigcontroller/v1alpha1"
	versioned "github.com/gbraxton/kconfig/pkg/client/clientset/versioned"
	internalinterfaces "github.com/gbraxton/kconfig/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/gbraxton/kconfig/pkg/client/listers/kconfigcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// KconfigInformer provides access to a shared informer and lister for
// Kconfigs.
type KconfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.KconfigLister
}

type kconfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKconfigInformer constructs a new informer for Kconfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKconfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKconfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKconfigInformer constructs a new informer for Kconfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKconfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KconfigcontrollerV1alpha1().Kconfigs(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KconfigcontrollerV1alpha1().Kconfigs(namespace).Watch(options)
			},
		},
		&kconfigcontrollerv1alpha1.Kconfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *kconfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKconfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *kconfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&kconfigcontrollerv1alpha1.Kconfig{}, f.defaultInformer)
}

func (f *kconfigInformer) Lister() v1alpha1.KconfigLister {
	return v1alpha1.NewKconfigLister(f.Informer().GetIndexer())
}
